

-- PROCESSO_COM_TRIAGEM
-- PROCESSO_SEM_TRIAGEM
-- TRIAGEM_SEM_PROCESSO
-- ########################################################################################
-- ################################## PROCESSOS SEM TRIAGEM ###############################

/*
 * RELACIONAMENTO ENTRE AS TABELAS "SACR_TEMPO_PROCESSO" e "TRIAGEM_ATENDIMENTO" É
 * DO TIPO "1:*", PRIMARY KEY CD_TRIAGEM_ATENDIMENTO, OPCIONAL.
 *
 * TESTANDO A RELACAO IDENTIFIQUEI:
 *      - 43 REGISTROS DISTINTOS SEM "CD_TRIAGEM_ATENDIMENTO" EM "SACR_TEMPO_PROCESSO"
 *        NAO PRESENTE EM "TRIAGEM_ATENDIMENTO"
 *      - VALIDANDO POR "CD_ATENDIMENTO" OS 43 REGISTROS NAO ESTAO PRESENTE EM
 *        "TRIAGEM_ATENDIMENTO"
*/

--      - CD_TRIAGEM_ATENDIMENTO MINUS CD_ATENDIMENTO
WITH PROCESSO_SEM_TRIAGEM
    AS (
        SELECT
            DISTINCT tcam.CD_ATENDIMENTO, tcam.CD_TRIAGEM_ATENDIMENTO
        FROM SACR_TEMPO_PROCESSO tcam
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM TRIAGEM_ATENDIMENTO tri
                WHERE tri.CD_TRIAGEM_ATENDIMENTO = tcam.CD_TRIAGEM_ATENDIMENTO --3470
        )

        MINUS -- 43 REGISTROS SEM "CD_TRIAGEM_ATENDIMENTO" EM "SACR_TEMPO_PROCESSO" QUE
              -- NAO ESTAO PRESENTES EM "TRIAGEM_ATENDIMENTO"

        SELECT
            DISTINCT tcam.CD_ATENDIMENTO, tcam.CD_TRIAGEM_ATENDIMENTO
        FROM SACR_TEMPO_PROCESSO tcam
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM TRIAGEM_ATENDIMENTO tri
                WHERE tcam.CD_ATENDIMENTO = tri.CD_ATENDIMENTO -- 3427
        )
        -- AND tcam.CD_ATENDIMENTO IN(246238, 1830221, 182978, 179551, 177592, 170815, 168646)
)
SELECT * FROM PROCESSO_SEM_TRIAGEM  ;



-- PROCESSOS SEM TRIAGEM
--      - CD_ATENDIMENTO MINUS CD_TRIAGEM_ATENDIMENTO
WITH PROCESSO_SEM_TRIAGEM
    AS (
        SELECT
            DISTINCT tcam.CD_ATENDIMENTO
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM SACR_TEMPO_PROCESSO tcam
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM TRIAGEM_ATENDIMENTO tri
                WHERE tcam.CD_ATENDIMENTO = tri.CD_ATENDIMENTO -- 3427
        )

        MINUS -- 0

        SELECT
            DISTINCT tcam.CD_ATENDIMENTO
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM SACR_TEMPO_PROCESSO tcam
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM TRIAGEM_ATENDIMENTO tri
                WHERE tri.CD_TRIAGEM_ATENDIMENTO = tcam.CD_TRIAGEM_ATENDIMENTO --3470
        )
)
SELECT * FROM PROCESSO_SEM_TRIAGEM  ;




-- INTERSECAO ENTRE AS TABELAS
WITH PROCESSO_SEM_TRIAGEM
    AS (
        SELECT
            DISTINCT tcam.CD_ATENDIMENTO
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM SACR_TEMPO_PROCESSO tcam
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM TRIAGEM_ATENDIMENTO tri
                WHERE tcam.CD_ATENDIMENTO = tri.CD_ATENDIMENTO -- 3427
        )

        INTERSECT -- 3428

        SELECT
            DISTINCT tcam.CD_ATENDIMENTO
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM SACR_TEMPO_PROCESSO tcam
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM TRIAGEM_ATENDIMENTO tri
                WHERE tri.CD_TRIAGEM_ATENDIMENTO = tcam.CD_TRIAGEM_ATENDIMENTO --3470
        )
)
SELECT * FROM PROCESSO_SEM_TRIAGEM
;


-- ###########################################################################################
-- #################################### TRIAGEM SEM PROCESSO #################################

/*
 * RELACIONAMENTO ENTRE AS TABELAS "TRIAGEM_ATENDIMENTO" e  É
 * DO TIPO "1:*", PRIMARY KEY CD_TRIAGEM_ATENDIMENTO, OPCIONAL.
 *
 * TESTANDO A RELACAO IDENTIFIQUEI:
 *      - VALIDANDO A RELACAO POR "CD_TRIAGEM_ATENDIMENTO" 7 REGISTROS DISTINTOS DE "TRIAGEM_ATENDIMENTO"
 *        NAO ESTAO PRESENTES EM "SACR_TEMPO_PROCESSO"
 *
 *      - VALIDANDO A RELACAO POR "CD_ATENDIMENTO" 34 REGISTROS ESTAO PRESENTES EM TRIAGEM E NAO ESTAO
 *        PRESENTE EM "SACR_TEMPO_PROCESSO" e VARIOS OUTROS REGISTROS NULL; AO VERIFICAR
 *        "CD_TRIAGEM_ATENDIMENTO" EM "SACR_TEMPO_PROCESSO" OS "CD_TRIAGEM_ATENDIMENTO" EXISTEM, ISTO QUER
 *        DIZER QUE O "CD_ATENDIMENTO" SO NAO FOI ALIMENTADO "SACR_TEMPO_PROCESSO" e QUE A RELACAO CORRETA
 *        E POR "CD_TRIAGEM_ATENDIMENTO"
*/

WITH TRIAGEM_SEM_PROCESSO
    AS (
        SELECT
            DISTINCT tri.CD_ATENDIMENTO, tri.CD_TRIAGEM_ATENDIMENTO, CD_FILA_SENHA
            -- COUNT(DISTINCT tri.CD_ATENDIMENTO) AS QTD
        FROM TRIAGEM_ATENDIMENTO tri
        WHERE
            NOT EXISTS (
                SELECT *
                FROM SACR_TEMPO_PROCESSO tcam
                WHERE
                    tcam.CD_ATENDIMENTO = tri.CD_ATENDIMENTO -- 34

                    -- tcam.CD_ATENDIMENTO IN(210609, 231178, 237983, 247868,
                    -- 252859, 253330, 264823, 271190, 272935) -- TRIAGEM SEM PROCESSO

                    -- tcam.CD_TRIAGEM_ATENDIMENTO IN(272326, 300795, 310053, 323785, 330892, 331561,
                    -- 347873, 356612, 359132, 365069, 364980, 364750) -- TRIAGEM SEM PROCESSO (COM PRECESSO ?!)

        )

        MINUS

        SELECT
            DISTINCT tri.CD_ATENDIMENTO, tri.CD_TRIAGEM_ATENDIMENTO, CD_FILA_SENHA
            -- COUNT(DISTINCT tri.CD_ATENDIMENTO) AS QTD
        FROM TRIAGEM_ATENDIMENTO tri
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM SACR_TEMPO_PROCESSO tcam
                WHERE tcam.CD_TRIAGEM_ATENDIMENTO = tri.CD_TRIAGEM_ATENDIMENTO -- NULL
        )
)
SELECT * FROM TRIAGEM_SEM_PROCESSO  ;




WITH TRIAGEM_SEM_PROCESSO
    AS (
        SELECT
            DISTINCT tri.CD_ATENDIMENTO, tri.CD_TRIAGEM_ATENDIMENTO, CD_FILA_SENHA
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM TRIAGEM_ATENDIMENTO tri
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM SACR_TEMPO_PROCESSO tcam
                WHERE tcam.CD_TRIAGEM_ATENDIMENTO = tri.CD_TRIAGEM_ATENDIMENTO -- NULL
        )

        MINUS

        SELECT
            DISTINCT tri.CD_ATENDIMENTO, tri.CD_TRIAGEM_ATENDIMENTO, CD_FILA_SENHA
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM TRIAGEM_ATENDIMENTO tri
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM SACR_TEMPO_PROCESSO tcam
                WHERE tcam.CD_ATENDIMENTO = tri.CD_ATENDIMENTO -- 34
        )
)
SELECT * FROM TRIAGEM_SEM_PROCESSO  ;




WITH TRIAGEM_SEM_PROCESSO
    AS (
        SELECT
            DISTINCT tri.CD_ATENDIMENTO, tri.CD_TRIAGEM_ATENDIMENTO, CD_FILA_SENHA
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM TRIAGEM_ATENDIMENTO tri
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM SACR_TEMPO_PROCESSO tcam
                WHERE tri.CD_ATENDIMENTO = tcam.CD_ATENDIMENTO --34
        )

        INTERSECT

        SELECT
            DISTINCT tri.CD_ATENDIMENTO, tri.CD_TRIAGEM_ATENDIMENTO, CD_FILA_SENHA
            -- COUNT(DISTINCT tcam.CD_ATENDIMENTO) AS QTD
        FROM TRIAGEM_ATENDIMENTO tri
        WHERE
            NOT EXISTS (
                SELECT 1
                FROM SACR_TEMPO_PROCESSO tcam
                WHERE tri.CD_TRIAGEM_ATENDIMENTO = tcam.CD_TRIAGEM_ATENDIMENTO -- NULL
        )
)
SELECT * FROM TRIAGEM_SEM_PROCESSO  ;