

SELECT COUNT(*) AS QTD
FROM DBAMV.IT_AGENDA_CENTRAL it
INNER JOIN AGENDA_CENTRAL agc      ON it.CD_AGENDA_CENTRAL = agc.CD_AGENDA_CENTRAL
WHERE agc.CD_AGENDA_CENTRAL = 49696
;


SELECT
    aci.*,
    ROW_NUMBER() OVER (
        PARTITION BY aci.cd_agenda_central
        ORDER BY aci.cd_item_agendamento ASC
    ) AS rn
FROM agenda_central_item_agenda aci
WHERE CD_AGENDA_CENTRAL = 49696
;

-- BUCKETS DE AGENDA
SELECT
    *
FROM DBAMV.IT_AGENDA_CENTRAL
WHERE
    -- EXTRACT(YEAR FROM HR_AGENDA) = 2025 AND
    CD_AGENDA_CENTRAL = 23887 --49696 --33422
    -- CD_ITEM_AGENDAMENTO IN(14, 15, 44, 335, 336, 447, 594, 764)
    -- CD_AGENDA_CENTRAL IN( 3958, 34100)
    -- CD_IT_AGENDA_CENTRAL = 594119 -- 23887
    -- CD_ATENDIMENTO = 242621
;

-- AGENDAS DA ESCALA
SELECT
    *
FROM DBAMV.AGENDA_CENTRAL
WHERE CD_AGENDA_CENTRAL = 23887
-- WHERE CD_AGENDA_CENTRAL IN( 3958, 34100)
;

-- PROCEDIMENTOS AGENDADOS VINCULADOS À AGENDA[AGENDA_CENTRAL] e AOS BUCKETS[IT_AGENDA_CENTRAL]
SELECT
    b.*
FROM DBAMV.AGENDA_CENTRAL_ITEM_AGENDA a
LEFT JOIN DBAMV.ITEM_AGENDAMENTO b ON a.CD_ITEM_AGENDAMENTO = b.CD_ITEM_AGENDAMENTO
-- WHERE CD_ITEM_AGENDAMENTO IN(14, 15, 44, 335, 336, 447, 594, 764)
WHERE CD_AGENDA_CENTRAL = 23887 --33422 --IN( 3958, 34100)
;


SELECT
    *
FROM DBAMV.ITEM_AGENDAMENTO
WHERE
    -- EXTRACT(YEAR FROM HR_AGENDA) = 2025 AND
    -- CD_ITEM_AGENDAMENTO = 1843
    CD_AGENDA_CENTRAL = 23887
;

-- SEM REGISTROS
SELECT
    d.*
FROM DBAMV.ITEM_AGENDAMENTO ia
JOIN DBAMV.ITEM_AGENDMTO_ITEM_AGEN_CTRAL d ON ia.CD_ITEM_AGENDAMENTO = d.CD_ITEM_AGENDAMENTO
WHERE d.CD_IT_AGENDA_CENTRAL IN(777388, 777389, 777390, 777391, 777392)

;



SELECT
    *
FROM DBAMV.ITEM_AGENDAMENTO ia
JOIN DBAMV.IT_AGENDA_CENTRAL d ON ia.CD_ITEM_AGENDAMENTO = d.CD_ITEM_AGENDAMENTO
WHERE CD_AGENDA_CENTRAL = 23887
;