
-- TELA MV:
-- M_ENTRADA_SERV -> Registrar a entrada de serviços, associando-a ou não a uma ordem de compra.
-- CAMINHO: Materiais e Logistica >> Almoxarifado >> Movimentações >> Entradas >> Entrada de Serviços

-- REGRAS:
-- LANCAMENTO DE NFSe 3 DIAS UTEIS ANTES DO VENCIMENTO

-- CASES:
-- ENT_SERV.CD_ENT_SERV = 8819




--SETOR TI - CD_SETOR IN(12, 73)
SELECT
    CD_RATCON_PAG,
    CD_CON_PAG,
    CD_SETOR,
    CD_REDUZIDO,
    CD_ITEM_RES,
    DT_COMPETENCIA,
    VL_RATEIO
FROM DBAMV.RATCON_PAG
WHERE CD_SETOR IN(12, 73)
;



--PREVISTOS NO FINANCEIRO (CONTAS A PAGAR)

/*
* NOTAS:
*   - NR_DOCUMENTO + CD_FORNECEDOR -> TORNA POSSIVEL JOIN COM "DBAMV.ENT_SERV"
*   -
*
*/

SELECT
    CD_CON_PAG,
    CD_PROCESSO,
    CD_REDUZIDO,
    CD_TIP_DOC,
    CD_FORNECEDOR,
    DS_CON_PAG,
    NR_DOCUMENTO,
    NR_SERIE,
    DT_LANCAMENTO,
    TP_VENCIMENTO,
    VL_BRUTO_CONTA
FROM DBAMV.CON_PAG
-- WHERE CD_CON_PAG = 66696
WHERE NR_DOCUMENTO = '4448' AND CD_FORNECEDOR = 3530
;



-- CONTAS A PAGAR (PARCELAS)
SELECT
    CD_ITCON_PAG,
    CD_CON_PAG,
    CD_PROCESSO,
    NR_PARCELA,
    DT_VENCIMENTO,
    DT_PREVISTA_PAG,
    TP_QUITACAO, -- "Q" QUITADO
    VL_DUPLICATA
FROM DBAMV.ITCON_PAG
WHERE CD_CON_PAG = 66696
-- WHERE CD_ITCON_PAG = 143636
;



-- PAGAMENTOS REALIZADOS

/*
* NOTAS:
*   - CALCULAR PAGAMENTOS FORA DE PRAZO
*       - ( DBAMV.PAGCON_PAG.DT_PAGAMENTO - DBAMV.ITCON_PAG.DT_VENCIMENTO )
*/
SELECT
    CD_PAGCON_PAG,
    CD_ITCON_PAG,
    CD_REDUZIDO,
    CD_PROCESSO,
    CD_ACRESCIMO,
    CD_DESCONTO,
    DS_PAGCON_PAG,
    DT_PAGAMENTO,
    DT_BAIXA,
    TP_PAGAMENTO,
    VL_ACRESCIMO,
    VL_DESCONTO,
    VL_PAGO
FROM DBAMV.PAGCON_PAG
WHERE CD_ITCON_PAG = 143636 -- CD_ITCON_PAG DA "CD_CON_PAG = 66696"
;



-- ESCRITURACAO DAS ENTRADAS

/*
* NOTAS:
*   - NR_DOCUMENTO + CD_FORNECEDOR -> TORNA POSSIVEL JOIN COM "DBAMV.CON_PAG"
*   - LANCAMENTOS SEM REGISTRO EM "DBAMV.CON_PAG" SIGNIFICA:
*       - PAGAMENTO SEM PREVISAO NO 'CONTAS A PAGAR'
*       - CALCULAR TEMPO QUE DEMOROU PARA ENTRAR NA PREVISAO:
*           - ( DBAMV.CON_PAG.DT_LANCAMENTO - DBAMV.ENT_SERV.DT_ENTRADA )
*           * ESSE INDICADOR PODE MEDIR A EFETIVIDADE DO 'CONTAS A PAGAR'
*/

SELECT
    CD_ENT_SERV,
    CD_CON_PAG,
    CD_FORNECEDOR,
    CD_OFICINA,
    CD_TIP_DOC,
    CD_USUARIO,
    NR_DOCUMENTO,
    NR_SERIE,
    DT_ENTRADA,
    DT_EMISSAO,
    DS_OBSERVACAO,
    VL_TOTAL
FROM DBAMV.ENT_SERV
-- WHERE CD_CON_PAG = 66696
-- WHERE CD_ENT_SERV = 7741
WHERE NR_DOCUMENTO = '15982' AND CD_FORNECEDOR = 408
;



-- ITENT_SERV
-- DOC_ENT
-- DUPLICATA




SELECT
    CD_SETOR,
    NM_SETOR,
    CD_CEN_CUS
FROM DBAMV.SETOR
WHERE CD_SETOR IN(12, 73)
;


/*
* CALCULOS:
*   - VALORES DE FORNECEDORES POR DIA-VENCIMENTO:
*       - VISUALIZAR A FREQUENCIA DE VALORES POR DIA-VENCIMENTO
*       - CALCULAR NOTIFICACAO DE VENCIMENTO NO MES ATUAL
*         PARA FORNECEDORES SEM NOTAS LANCADAS NAS RESPECTIVAS
*         FREQUENCIAS DAQUELE VALOR
*/
SELECT
    CD_FORNECEDOR,
    CD_CIDADE,
    CD_SETOR,
    NM_FORNECEDOR,
    NM_FANTASIA,
    NR_CGC_CPF
FROM DBAMV.FORNECEDOR
;



-- DBAMV.HISTORICO_PRORROGACAO
-- DBAMV.MOTIVO_PRORROGACAO


