

WITH AVALIACAO
    AS (
        SELECT
            pa.CD_ATENDIMENTO,
            dc.CD_PACIENTE,
            pa.CD_DOCUMENTO_CLINICO,
            dc.DH_DOCUMENTO,
            dc.DH_CRIACAO,
            pf.DS_FORMULA,
            dc.NM_DOCUMENTO,
            pa.NM_USUARIO
        FROM DBAMV.PAGU_FORMULA pf
        LEFT JOIN DBAMV.PAGU_AVALIACAO pa ON pf.CD_FORMULA = pa.CD_FORMULA
        LEFT JOIN DBAMV.PW_DOCUMENTO_CLINICO dc ON pa.CD_DOCUMENTO_CLINICO = dc.CD_DOCUMENTO_CLINICO
        WHERE pf.CD_FORMULA IN(111, 112)
),
ATENDIMENTO
    AS (
        SELECT a.*
        FROM DBAMV.ATENDIME a
        WHERE a.TP_ATENDIMENTO = 'I'
),
PACIENT
    AS (
        SELECT
            p.CD_PACIENTE,
            p.NM_PACIENTE,
            p.DT_NASCIMENTO,
            DBAMV.fn_idade_paciente(p.CD_PACIENTE, NULL) AS IDADE
        FROM DBAMV.PACIENTE p
),
LEITINHO
    AS (
        SELECT
            l.CD_LEITO,
            l.DS_LEITO
        FROM DBAMV.LEITO l
),
USERR
    AS (
        SELECT
            u.CD_USUARIO,
            u.NM_USUARIO
        FROM DBASGU.USUARIOS u
),
BASE_INFO AS (
    SELECT
        a.CD_ATENDIMENTO,
        a.CD_PACIENTE,
        a.CD_LEITO,
        a.DT_ATENDIMENTO,
        a.DT_ALTA,
        av.DH_DOCUMENTO,
        av.DH_CRIACAO,
        av.DS_FORMULA,
        u.NM_USUARIO,
        p.NM_PACIENTE,
        p.DT_NASCIMENTO,
        DBAMV.fn_idade_paciente(p.CD_PACIENTE, NULL) AS IDADE,
        l.DS_LEITO,
        a.TP_ATENDIMENTO
    FROM ATENDIMENTO a
    LEFT JOIN AVALIACAO av ON av.CD_ATENDIMENTO = a.CD_ATENDIMENTO
    LEFT JOIN PACIENT p ON a.CD_PACIENTE = p.CD_PACIENTE
    LEFT JOIN LEITINHO l ON a.CD_LEITO = l.CD_LEITO
    LEFT JOIN USERR u ON av.NM_USUARIO = u.CD_USUARIO
    WHERE a.DT_ATENDIMENTO >= ADD_MONTHS(SYSDATE, -4)
    AND DBAMV.fn_idade_paciente(p.CD_PACIENTE, NULL) >= 60
),
DIAS AS (
    SELECT LEVEL - 1 AS DIA
    FROM DUAL
    CONNECT BY LEVEL <= 100 -- limite de até 100 dias de internação
)
SELECT
    b.CD_ATENDIMENTO,
    b.CD_PACIENTE,
    b.NM_PACIENTE,
    b.DT_NASCIMENTO,
    b.IDADE,
    b.CD_LEITO,
    b.DS_LEITO,
    b.TP_ATENDIMENTO,
    b.DT_ATENDIMENTO,
    b.DT_ALTA,
    b.DT_ATENDIMENTO + d.DIA AS DT_GERADA,
    CASE WHEN TRUNC(b.DT_ATENDIMENTO + d.DIA) = TRUNC(b.DH_DOCUMENTO) THEN
        b.DH_DOCUMENTO
    ELSE NULL
    END AS DH_DOCUMENTO,
    CASE WHEN TRUNC(b.DT_ATENDIMENTO + d.DIA) = TRUNC(b.DH_DOCUMENTO) THEN
        b.DH_CRIACAO
    ELSE NULL
    END AS DH_CRIACAO,
    CASE
        WHEN TRUNC(b.DT_ATENDIMENTO + d.DIA) = TRUNC(b.DH_DOCUMENTO)
        THEN b.DS_FORMULA
        ELSE NULL
    END AS DS_FORMULA,
        CASE
        WHEN TRUNC(b.DT_ATENDIMENTO + d.DIA) = TRUNC(b.DH_DOCUMENTO)
        THEN b.NM_USUARIO
        ELSE NULL
    END AS NM_USUARIO
FROM BASE_INFO b
JOIN DIAS d ON d.DIA <= COALESCE(b.DT_ALTA, SYSDATE) - b.DT_ATENDIMENTO
ORDER BY b.CD_ATENDIMENTO, b.DT_ATENDIMENTO + d.DIA DESC
;

WHERE b.CD_ATENDIMENTO = 203882



JUNTA_TUDO_E_JOGA_FORA ( CD_ATENDIMENTO, DS_FORMULA, NM_USUARIO, CD_PACIENTE, NM_PACIENTE,
 DT_NASCIMENTO, IDADE, CD_LEITO, DS_LEITO, DT_ATENDIMENTO, DT_ALTA, DT_GERADA, TP_ATENDIMENTO )
    AS (
        SELECT
            a.CD_ATENDIMENTO,
            av.DS_FORMULA,
            u.NM_USUARIO,
            a.CD_PACIENTE,
            p.NM_PACIENTE,
            p.DT_NASCIMENTO,
            p.IDADE,
            a.CD_LEITO,
            l.DS_LEITO,
            a.DT_ATENDIMENTO,
            a.DT_ALTA,
            -- av.DH_DOCUMENTO,
            -- av.DH_CRIACAO,
            a.DT_ATENDIMENTO as DT_GERADA,
            a.TP_ATENDIMENTO
        FROM ATENDIMENTO a
        LEFT JOIN AVALIACAO av ON a.CD_ATENDIMENTO = av.CD_ATENDIMENTO
        LEFT JOIN PACIENT p ON a.CD_PACIENTE = p.CD_PACIENTE
        LEFT JOIN LEITINHO l ON a.CD_LEITO = l.CD_LEITO
        LEFT JOIN USERR u ON av.NM_USUARIO = u.CD_USUARIO
        WHERE a.TP_ATENDIMENTO = 'I'
        AND p.IDADE >= 60
        AND a.DT_ATENDIMENTO >= ADD_MONTHS(SYSDATE, -4)

        UNION ALL

        SELECT
            a.CD_ATENDIMENTO,
            av.DS_FORMULA,
            u.NM_USUARIO,
            a.CD_PACIENTE,
            p.NM_PACIENTE,
            p.DT_NASCIMENTO,
            p.IDADE,
            a.CD_LEITO,
            l.DS_LEITO,
            a.DT_ATENDIMENTO,
            a.DT_ALTA,
            -- av.DH_DOCUMENTO,
            -- av.DH_CRIACAO,
            j.DT_GERADA + 1,
            a.TP_ATENDIMENTO
        FROM ATENDIMENTO a
        LEFT JOIN AVALIACAO av ON a.CD_ATENDIMENTO = av.CD_ATENDIMENTO
        LEFT JOIN PACIENT p ON a.CD_PACIENTE = p.CD_PACIENTE
        LEFT JOIN LEITINHO l ON a.CD_LEITO = l.CD_LEITO
        LEFT JOIN USERR u ON av.NM_USUARIO = u.CD_USUARIO
        INNER JOIN JUNTA_TUDO_E_JOGA_FORA j ON j.DT_ATENDIMENTO = a.DT_ATENDIMENTO AND j.DT_ALTA = a.DT_ALTA
        WHERE j.DT_GERADA + 1 < COALESCE(a.DT_ALTA, SYSDATE) AND j.DT_GERADA +1  < COALESCE(a.DT_ALTA, SYSDATE)
        AND a.TP_ATENDIMENTO = 'I'
        AND p.IDADE >= 60
        AND a.DT_ATENDIMENTO >= ADD_MONTHS(SYSDATE, -4)
)
SELECT * FROM JUNTA_TUDO_E_JOGA_FORA WHERE CD_ATENDIMENTO = 206697
;









SELECT
    pa.CD_ATENDIMENTO,
    dc.CD_PACIENTE,
    pa.CD_DOCUMENTO_CLINICO,
    dc.DH_DOCUMENTO,
    dc.DH_CRIACAO,
    pf.DS_FORMULA,
    dc.NM_DOCUMENTO,
    pa.NM_USUARIO
FROM DBAMV.PAGU_FORMULA pf
LEFT JOIN DBAMV.PAGU_AVALIACAO pa ON pf.CD_FORMULA = pa.CD_FORMULA
LEFT JOIN DBAMV.PW_DOCUMENTO_CLINICO dc ON pa.CD_DOCUMENTO_CLINICO = dc.CD_DOCUMENTO_CLINICO
WHERE pf.CD_FORMULA IN(111, 112) AND pa.CD_ATENDIMENTO = 206133;
